### ISSUE TITLE
About source Mod Menu (continue)

### ISSUE THREAD

**Issue by thienha1** [JMBQ/Honkai-Impact-3-mod#10]
Like this?
![Capture](https://user-images.githubusercontent.com/18132856/209959041-656349aa-27ac-4a37-ba21-981f1015fe52.PNG)

**Comment by JMBQ** [comment]
After reading your code, it's not clear to me what you want to do
```
static {
    system.loadLibrary("xxxx");
}
```
This codes directly determines that the dynamic libraries in the lib directory will be loaded at runtime, and there is no need for the OpenAssest method below (the correct method  name is copyAssets)

**Comment by thienha1** [comment]
hmm i just want to build library and load it like your project
Your guide:
![Untitled2](https://raw.githubusercontent.com/JMBQ/image/main/Honkai-Impact-3-mod/05.png)
What I want:
![Untitled2](https://user-images.githubusercontent.com/18132856/210130026-ebdecc9b-7e90-4daa-81e5-23901404a7a7.png)
And I really dunno it work or not on mobile.
Here is what i change in my project:
**_Main.java_**
```
public class Main {

    //Load lib
    static {
        // When you change the lib name, change also on Android.mk file
        // Both must have same name
        System.loadLibrary("GamePro");
    }

    private static native void CheckOverlayPermission(Context context);

    public static void StartWithoutPermission(Context context) {
        CrashHandler.init(context, true);
        if (context instanceof Activity) {
            //Check if context is an Activity.
            Menu menu = new Menu(context);
            menu.SetWindowManagerActivity();
            menu.ShowMenu();
        } else {
            //Anything else, ask for permission
            CheckOverlayPermission(context);
        }
    }

    public static void copyAssets(Context context, String fileName) throws IOException {
        File file = new File(context.getFilesDir().getAbsolutePath() + File.separator + fileName);
        if (!file.exists() || file.length() == 0) {
            FileOutputStream fos = new FileOutputStream(file);
            InputStream inputStream = context.getAssets().open(fileName);
            int len;
            byte[] buffer = new byte[1024];
            while (-1 != (len = inputStream.read(buffer))) {
                fos.write(buffer, 0, len);
            }
            fos.flush();
            inputStream.close();
            fos.close();
        }
    }

    public static void Start(Context context) {
        CrashHandler.init(context, false);

        CheckOverlayPermission(context);
    }
 }


```
Then I build apk and move lib so files into assets and rename libGamePro.so to libGamePro
And i did remaining steps as guide in Android Mod Menu.
So will it pass lib check and apk signature verification?

**Comment by JMBQ** [comment]
I know exactly what you mean.

My code is quite changed, so it is not convenient to give you the source code directly, including how to load the lib of files directory

First, it is true that your server does not have signature verification, it has lib directory verification.
Second, it's not as simple as changing the name and putting it into assets, it requires a series of steps to complete, and these steps can actually be done by directly decompiling my smali file to get the source code.
Again, if you can't decompile, I can show you a tricky way to bypass the lib detection.
Your code only needs to change this
```
//Load lib
    static {
        System.loadLibrary("xcrash_dumper");
    }
```

Change the name of your dynamic library to "xcrash_dumper", then drop the generated dynamic library into the game's lib directory to replace the original xcrash_dumper, so you can bypass the detection, very simple, right?

**Comment by JMBQ** [comment]
Loading files lib is actually very simple, but I saw that you didn't really call the code I gave you, and that's when I knew that maybe you weren't very clear about what they meant, so I was lazy and didn't copy the source code for you, but just told you the easiest way to bypass

**Comment by thienha1** [comment]
> Loading files lib is actually very simple, but I saw that you didn't really call the code I gave you, and that's when I knew that maybe you weren't very clear about what they meant, so I was lazy and didn't copy the source code for you, but just told you the easiest way to bypass

Yeah, i admitted that i didnt know how to use it so i just follow your simple ways then another issue coming for me is that can't compile after decompile apk.
![Untitled](https://user-images.githubusercontent.com/18132856/210152506-bcecfe24-5064-4b5d-9c9a-70c31feef0a9.png)
It so close to find out it work or not but this error block me.

**Comment by JMBQ** [comment]
unable to rename ...
Maybe you are taking it up, try compiling again.

**Comment by thienha1** [comment]
> unable to rename ... Maybe you are taking it up, try compiling again.

i tried and still not work
