### ISSUE TITLE
Honkai: Star Rail

### ISSUE THREAD

**Issue by thienha1** [JMBQ/Honkai-Impact-3-mod#16]
This game has been opened today, can you interest in? So do you has plan to mod this game?

**Comment by JMBQ** [comment]
As far as I know, this game is currently only available in Chinese, are you sure you can understand Chinese?  

It should have no simple mods, it has dex checks and other checks.

you either tear the checks by hand, or relocate it to bypass the checks

**Comment by thienha1** [comment]
Yeah and it opened 6 days ago, and did u find out how to bypass checks?

**Comment by thienha1** [comment]
I tried and this game dont let me in


https://user-images.githubusercontent.com/18132856/235576206-07c4282c-86c7-41a9-8c94-c7d8d2a3bde7.mp4

**Comment by JMBQ** [comment]
> I tried and this game dont let me in我试过了，这个游戏不让我进去
> 
>  Honkai_Star_Rail.mp4


https://user-images.githubusercontent.com/78288131/235706389-6b5cf772-3bdc-4127-a547-acdd088ea549.mp4

You need to bypass the dex check
