### ISSUE TITLE
Always crashes in LDPlayer 9 64 bit (SEA server)

### ISSUE THREAD

**Issue by Rempacious** [JMBQ/Honkai-Impact-3-mod#17]
https://github.com/JMBQ/Honkai-Impact-3-mod/assets/73411987/48651750-8ac7-4429-b071-244f030760fa
![image](https://github.com/JMBQ/Honkai-Impact-3-mod/assets/73411987/de4384d6-e5df-4ba5-99cd-9ff1ec2ed28c)
![image](https://github.com/JMBQ/Honkai-Impact-3-mod/assets/73411987/921124c8-265c-46e1-8301-29b33865471c)

Always getting crashing in SEA server, I'm sure I did it all right

**Comment by JMBQ** [comment]
32-bit emulators are no longer supported.
nox9 (64-bit), Recommendation 100%
ldplayer9 (64-bit), Recommendation50%

u can try nox9 (64-bit), ldplayer9 maybe crash

**Comment by Rempacious** [comment]
I installed Nox and tried it there did as you instructed but lib/arm64/ doesn't seem to exist and only /arm/ 
![Screenshot_20230513-225018](https://github.com/JMBQ/Honkai-Impact-3-mod/assets/73411987/2248e804-f0d5-4814-bf49-d837fba9246a)

**Comment by JMBQ** [comment]
> I installed Nox and tried it there as you instructed but lib/arm64/ doesn't seem to exist and only /arm/ 
> ![Screenshot_20230513-225018](https://github.com/JMBQ/Honkai-Impact-3-mod/assets/73411987/2248e804-f0d5-4814-bf49-d837fba9246a)
> 

I need to make sure you know how to adb connect to nox9, this situation needs to be resolved by executing the adb command. If you are not sure how to adb connect, you can google it and afterwards you can reply to me and I will tell you what command to enter

**Comment by Rempacious** [comment]
Thank you very much for the help but I just resolved it by downloading the arm64 version from playstore. I've been using the one in official website which is the reason it just gives arm.

![Screenshot_20230513-233932](https://github.com/JMBQ/Honkai-Impact-3-mod/assets/73411987/5bc63a54-4c5d-44eb-b734-2990260d01bf)
