### ISSUE TITLE
请问一下重新编译后出现错误的问题

### ISSUE THREAD

**Issue by sherlokcerry** [JMBQ/Honkai-Impact-3-mod#19]
对东南亚服6.6版本的安装包反编译并进行了有关文件的修改后，重新编译时出现了以下问题：
2023/5/18 13:38:52

java version "19.0.2" 2023-01-17
Java(TM) SE Runtime Environment (build 19.0.2+7-44)
Java HotSpot(TM) 64-Bit Server VM (build 19.0.2+7-44, mixed mode, sharing)
---------------------------

Decompiling APK file... (Press ESC to cancel)
Command: java.exe  -jar "D:\APKEASYTOOL\Apktool\apktool_2.6.1.jar" d -f --only-main-classes -o "D:\APKEASYTOOL\1-Decompiled APKs\20230510-143703-oversea_android_sim-Global-v6_6-final-123423f2c8de-4407-6.6.0-ASB-Win100-Agent1-1320_signed" "E:\崩坏安装包\20230510-143703-oversea_android_sim-Global-v6_6-final-123423f2c8de-4407-6.6.0-ASB-Win100-Agent1-1320_signed.apk"

I: Using Apktool 2.6.1 on 20230510-143703-oversea_android_sim-Global-v6_6-final-123423f2c8de-4407-6.6.0-ASB-Win100-Agent1-1320_signed.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\澶忔礇鍏媆AppData\Local\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
Lcom/ano/gshell/AnoApplication;-><clinit>()V: Invalid debug offset
Lcom/ano/gshell/AnoApplication;-><init>()V: Invalid debug offset
Lcom/ano/gshell/AnoApplication;->dec(Ljava/lang/String;)Ljava/lang/String;: Invalid debug offset
Lcom/ano/gshell/AnoApplication;->dec(Ljava/lang/String;)Ljava/lang/String;: Invalid debug offset
Lcom/ano/gshell/AnoApplication;->attachBaseContext(Landroid/content/Context;)V: Invalid debug offset
Lcom/ano/gshell/AnoApplication;->attachBaseContext(Landroid/content/Context;)V: Invalid debug offset
I: Baksmaling classes2.dex...
I: Baksmaling classes3.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
I: Copying META-INF/services directory
Decompile successful.
---------------------------

Compiling APK file... (Press ESC to cancel)
Command: java.exe -jar "D:\APKEASYTOOL\Apktool\apktool_2.6.1.jar" b -f --use-aapt2 -o "D:\APKEASYTOOL\2-Recompiled APKs\20230510-143703-oversea_android_sim-Global-v6_6-final-123423f2c8de-4407-6.6.0-ASB-Win100-Agent1-1320_signed.apk" "D:\APKEASYTOOL\1-Decompiled APKs\20230510-143703-oversea_android_sim-Global-v6_6-final-123423f2c8de-4407-6.6.0-ASB-Win100-Agent1-1320_signed"

I: Using Apktool 2.6.1
I: Smaling smali folder into classes.dex...
I: Smaling smali_classes2 folder into classes2.dex...
I: Smaling smali_classes3 folder into classes3.dex...
I: Smaling smali_classes4 folder into classes4.dex...
I: Building resources...
W: error: could not open extensions file C:\Users\澶忔礇鍏媆AppData\Local\Temp\APKTOOL13623534912436029842.tmp for reading.
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\admin\AppData\Local\Temp\brut_util_Jar_86488303464049127151083193670981633738.tmp, link, -o, C:\Users\admin\AppData\Local\Temp\APKTOOL2209023926116470878.tmp, --package-id, 127, --min-sdk-version, 21, --target-sdk-version, 31, --version-code, 560, --version-name, 6.6.0, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, -e, C:\Users\admin\AppData\Local\Temp\APKTOOL13623534912436029842.tmp, -0, arsc, -I, C:\Users\admin\AppData\Local\apktool\framework\1.apk, --manifest, D:\APKEASYTOOL\1-Decompiled APKs\20230510-143703-oversea_android_sim-Global-v6_6-final-123423f2c8de-4407-6.6.0-ASB-Win100-Agent1-1320_signed\AndroidManifest.xml, D:\APKEASYTOOL\1-Decompiled APKs\20230510-143703-oversea_android_sim-Global-v6_6-final-123423f2c8de-4407-6.6.0-ASB-Win100-Agent1-1320_signed\build\resources.zip]
Compile failed. Please read the log

Click here for more infomation about Apktool issues
https://forum.xda-developers.com/t/tool-windows-apk-easy-tool-v1-58-3-dec-2020.3333960/#post-65775601
因为我并不懂JAVA有关知识，不知如何解决。所以烦请您看看这项问题出于什么原因，谢谢！

**Comment by sherlokcerry** [comment]
我之前使用的是在6.5版本成功反编译、编译的apkeasytool，这次没能成功，后重新下载使用了apkeasytoolv1.60 Portable版本，解压后apktool文件夹里apktool-2.6.1.jar而不是2.7.1版本，我从搜索引擎中搜索得到了apktool-2.7.1文件并用其替换了原来的2.6.1文件。完成release里的步骤后仍出现了以下问题。
2023/5/18 19:44:08

java version "19.0.2" 2023-01-17
Java(TM) SE Runtime Environment (build 19.0.2+7-44)
Java HotSpot(TM) 64-Bit Server VM (build 19.0.2+7-44, mixed mode, sharing)
---------------------------

正在反编译 APK 文件... (按下 ESC 取消)
Command: java.exe  -jar "E:\HonkaiCheat\AETP\Apktool\apktool-2.7.1.jar" d -f --only-main-classes -o "E:\HonkaiCheat\AETP\1-Decompiled APKs\20230510-143703-oversea_android_sim-Global-v6_6-final-123423f2c8de-4407-6.6.0-ASB-Win100-Agent1-1320_signed" "E:\Honkai\SouthEastern\20230510-143703-oversea_android_sim-Global-v6_6-final-123423f2c8de-4407-6.6.0-ASB-Win100-Agent1-1320_signed.apk"

I: Using Apktool 2.7.1-cca94b-SNAPSHOT on 20230510-143703-oversea_android_sim-Global-v6_6-final-123423f2c8de-4407-6.6.0-ASB-Win100-Agent1-1320_signed.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\澶忔礇鍏媆AppData\Local\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
Lcom/ano/gshell/AnoApplication;-><clinit>()V: Invalid debug offset
Lcom/ano/gshell/AnoApplication;-><init>()V: Invalid debug offset
Lcom/ano/gshell/AnoApplication;->dec(Ljava/lang/String;)Ljava/lang/String;: Invalid debug offset
Lcom/ano/gshell/AnoApplication;->dec(Ljava/lang/String;)Ljava/lang/String;: Invalid debug offset
Lcom/ano/gshell/AnoApplication;->attachBaseContext(Landroid/content/Context;)V: Invalid debug offset
Lcom/ano/gshell/AnoApplication;->attachBaseContext(Landroid/content/Context;)V: Invalid debug offset
I: Baksmaling classes2.dex...
I: Baksmaling classes3.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
I: Copying META-INF/services directory
反编译成功
---------------------------

正在编译 APK 文件... (按下 ESC 取消)
Command: java.exe -jar "E:\HonkaiCheat\AETP\Apktool\apktool-2.7.1.jar" b -f --use-aapt2 -o "E:\HonkaiCheat\AETP\2-Recompiled APKs\20230510-143703-oversea_android_sim-Global-v6_6-final-123423f2c8de-4407-6.6.0-ASB-Win100-Agent1-1320_signed.apk" "E:\HonkaiCheat\AETP\1-Decompiled APKs\20230510-143703-oversea_android_sim-Global-v6_6-final-123423f2c8de-4407-6.6.0-ASB-Win100-Agent1-1320_signed"

I: Using Apktool 2.7.1-cca94b-SNAPSHOT
I: Smaling smali folder into classes.dex...
I: Smaling smali_classes2 folder into classes2.dex...
I: Smaling smali_classes3 folder into classes3.dex...
I: Smaling smali_classes4 folder into classes4.dex...
I: Building resources...
W: error: could not open extensions file C:\Users\澶忔礇鍏媆AppData\Local\Temp\APKTOOL14922820139961923303.tmp for reading.
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\admin\AppData\Local\Temp\brut_util_Jar_1853613099871947425197013436198179894.tmp, link, -o, C:\Users\admin\AppData\Local\Temp\APKTOOL13538513848690458023.tmp, --package-id, 127, --min-sdk-version, 21, --target-sdk-version, 31, --version-code, 560, --version-name, 6.6.0, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, C:\Users\admin\AppData\Local\Temp\APKTOOL14922820139961923303.tmp, -0, arsc, -I, C:\Users\admin\AppData\Local\apktool\framework\1.apk, --manifest, E:\HonkaiCheat\AETP\1-Decompiled APKs\20230510-143703-oversea_android_sim-Global-v6_6-final-123423f2c8de-4407-6.6.0-ASB-Win100-Agent1-1320_signed\AndroidManifest.xml, E:\HonkaiCheat\AETP\1-Decompiled APKs\20230510-143703-oversea_android_sim-Global-v6_6-final-123423f2c8de-4407-6.6.0-ASB-Win100-Agent1-1320_signed\build\resources.zip]
编译失败。 请阅读日志

请阅读常见问题解答和故障排除
https://forum.xda-developers.com/t/tool-windows-apk-easy-tool-v1-58-3-dec-2020.3333960/#post-65775601
不好意思，还请你再帮忙看看！谢谢！

**Comment by JMBQ** [comment]
axml修改错误，查这个

上传axml的尾部截图给我看看

**Comment by sherlokcerry** [comment]
> 

axml是AndroidManifest文件吗？

**Comment by JMBQ** [comment]
W: error: could not open extensions file 
C:\Users\澶忔礇鍏媆AppData\Local\Temp\APKTOOL14922820139961923303.tmp for reading.

这个读取失败，建议重启电脑，改成英文目录

**Comment by sherlokcerry** [comment]
> W: error: could not open extensions file C:\Users\澶忔礇鍏媆AppData\Local\Temp\APKTOOL14922820139961923303.tmp for reading.
> 
> 这个读取失败，建议重启电脑，改成英文目录

好的，我尝试一下，这个似乎是以我计算机管理员为名称的文件夹，我看看怎么修改。谢谢你。

**Comment by sherlokcerry** [comment]
很奇怪，因为上个版本6.5的的确确可以修改并且成功了，也没有更改过用户名，不知道为什么现在会出错误，管理员文件夹修改C:\Users\澶忔礇鍏媆AppData\Local\Temp似乎光修改管理员名称没效果。搜索到的教程均很复杂，只得做罢。感谢你耐心的回答。

**Comment by JMBQ** [comment]
我觉得你可以试着删除项目，清理干净，重新做一次，打包失败肯定是你电脑问题

**Comment by sherlokcerry** [comment]
问题解决了，的确是电脑的问题，仔细回忆了一下这段时间的变动，又根据文件夹的乱码情况，最后确定是修改了区域设置的原因
![image](https://github.com/JMBQ/Honkai-Impact-3-mod/assets/117138559/42e1c111-c8f6-48d8-9f2f-d4064567fc82)
谢谢你的提醒！

**Comment by JMBQ** [comment]
> 问题解决了，的确是电脑的问题，仔细回忆了一下这段时间的变动，又根据文件夹的乱码情况，最后确定是修改了区域设置的原因
> ![image](https://github.com/JMBQ/Honkai-Impact-3-mod/assets/117138559/42e1c111-c8f6-48d8-9f2f-d4064567fc82)
> 谢谢你的提醒！

那sea是否生效，我发现6.6游戏官方添加了特别保护

**Comment by sherlokcerry** [comment]
官方安装包可以正常安装打开，按步骤修改后，可以正常安装，但点击后打开游戏一直处于黑屏状态。

**Comment by JMBQ** [comment]
1.3.0对付不了新版保护，被保护发现后，黑屏

我在考虑是否更新1.4.0

破掉这个保护不是很难，难的是如何将1.4.0繁琐的操作流程简化

**Comment by sherlokcerry** [comment]
> 1.3.0对付不了新版保护，被保护发现后，黑屏
> 
> 我在考虑是否更新1.4.0
> 
> 破掉这个保护不是很难，难的是如何将1.4.0繁琐的操作流程简化

原来如此，祝您化繁为简的工作顺利进行。辅助功能很实用，很强大。不过在6.5版本的使用中，仅开启其中的几个功能进入战斗场景后游戏会卡住，且在游戏中关闭功能会出现同样的问题，作为使用者不知是什么原因。

**Comment by JMBQ** [comment]
> > 1.3.0对付不了新版保护，被保护发现后，黑屏
> > 
> > 我在考虑是否更新1.4.0
> > 
> > 破掉这个保护不是很难，难的是如何将1.4.0繁琐的操作流程简化
> 
> 原来如此，祝您化繁为简的工作顺利进行。辅助功能很实用，很强大。不过在6.5版本的使用中，仅开启其中的几个功能进入战斗场景后游戏会卡住，且在游戏中关闭功能会出现同样的问题，作为使用者不知是什么原因。

不应该啊，我直接hook掉目标偏移，开关只会影响方法走向，不至于卡住，我自己测试是没问题的，很流畅，你的手机运存多少

**Comment by sherlokcerry** [comment]
> 

目前使用的RedmiK50，手机运行内存是8G，8+3

**Comment by sherlokcerry** [comment]
> > > 1.3.0对付不了新版保护，被保护发现后，黑屏
> > > 我在考虑是否更新1.4.0
> > > 破掉这个保护不是很难，难的是如何将1.4.0繁琐的操作流程简化
> > 
> > 
> > 原来如此，祝您化繁为简的工作顺利进行。辅助功能很实用，很强大。不过在6.5版本的使用中，仅开启其中的几个功能进入战斗场景后游戏会卡住，且在游戏中关闭功能会出现同样的问题，作为使用者不知是什么原因。
> 
> 不应该啊，我直接hook掉目标偏移，开关只会影响方法走向，不至于卡住，我自己测试是没问题的，很流畅，你的手机运存多少

目前使用的RedmiK50，手机运行内存是8G，8+3

**Comment by JMBQ** [comment]
8g应该足够的，游戏卡住有我的一部分原因，如果我放弃调用运存做保护，那肯定不会卡住
