### ISSUE TITLE
Security in HI3

### ISSUE THREAD

**Issue by thienha1** [JMBQ/Honkai-Impact-3-mod#21]
I tried latest version in HI3 and this game crash instantly after i modified and recompile APK, any idea? Have u find out other solution for this? It seem look like HSR for now, same security but harder to bypass!!

**Comment by JMBQ** [comment]
yes now its harder than HSR, HI3 adds A protection identical to TProtect, HSR only have dex protection, trying..

**Comment by JMBQ** [comment]
![111.jpg](https://github.com/JMBQ/Honkai-Impact-3-mod/assets/78288131/50f260ce-156a-4953-a809-77d23f0bd5c0)

The protection strength of version 6.6 is basically equal to that of CN, the new protection cannot be broken by ordinary methods, and redirection is required

**Comment by thienha1** [comment]
> ![111.jpg](https://user-images.githubusercontent.com/78288131/239512694-50f260ce-156a-4953-a809-77d23f0bd5c0.jpg)
> 
> The new protection strength of version 6.6 is basically equal to that of CN, the new protection cannot be broken by ordinary methods, and redirection is required

So u just redirect server to bypass protect?

**Comment by JMBQ** [comment]
I got it wrong, it's much weaker than CN, maybe you can break it without using redirection
