### ISSUE TITLE
1.4.0将在0521发布

### ISSUE THREAD

**Issue by JMBQ** [JMBQ/Honkai-Impact-3-mod#22]
一开始，我以为ano是王者水平，和tprotect一个级别，连忙祭出重定向大法来搞它。但是到最后，发现它只是个白银弟弟。
不带这样玩人的啊，来点给力的挑战啊

**Comment by thienha1** [comment]
Will u still update source code too? It should be good if u update release 1.4.0 and update source code!!

**Comment by thienha1** [comment]
Your source code in 1.3.0 dont work for me, game got black screen after running game

**Comment by QuanYWZ** [comment]
期待

**Comment by JMBQ** [comment]
> 

No update for now, I call a lot of them and need time to separate
