### ISSUE TITLE
Hello Sir

### ISSUE THREAD

**Issue by sean7119** [JMBQ/Honkai-Impact-3-mod#3]
能否更新 v6.1.0呢？

**Comment by JMBQ** [comment]
未失效吧，用apkeasytool自行编译就完事了，简单得很

**Comment by JMBQ** [comment]
懒得编译就用我另一个项目的URC，手机解锁就能用

**Comment by sean7119** [comment]
> 未失效吧，用apkeasytool自行编译就完事了，简单得很

JMBQ sir~ 感謝您的指點, 我會嘗試尋找apkeasytool 自行操作, 如果操作過程有問題再跟您請教~多謝您

**Comment by sean7119** [comment]
[https://drive.google.com/file/d/17pXjWQ3pdu-Q-RXTz03oK7RmUQ8QNzW8/view?usp=share_link](url)

大大您好 我下載了APK Easy Tool V1.60
目前6.1版本的官方APK檔名是bh3_1027
反編輯成功  但沒有生成对应文件夹 > 接著點選"提取APK"  才生成文件夾
另外下載了Notepadplusplus 來編輯XML檔
但開啟了AndroidManifest.xml 之後, 畫面顯示的文字跟您食用方法的照片 
有很大的不同... 是否能請您指點一下呢

**Comment by sean7119** [comment]
[https://drive.google.com/file/d/1Og-0vFB2yfLax6hNynhPcCPw_qoa4H18/view?usp=sharing](url)
遊戲文件夾沒有 android\support 資料夾
也沒有找到 com\miHoYo\overridenativeactivity\OverrideNativeActivity.smali  資料夾

**Comment by JMBQ** [comment]
刚好录完安卓的，顺手把PC也录了，十几分钟的事

更新教程了，直接看video，解压后有视频，跟着做就行了

**Comment by sean7119** [comment]
JMBQ大大 感謝您, 稍早注意我自己操作錯誤的關鍵是雖然下載的apk easy tool 是1.6版本, 但其實是 2.4.3 不是2.6.1
所以其他同學想要學習的, 請務必確認自己下載的 apk easy tool  是2.6.1 才能正確依照JMBQ老師的教程  再次感謝~

**Comment by JMBQ** [comment]
> JMBQ大大您好 能否再跟您請益呢... 我是從官網下載APK 檔名 bh3_1027.apk https://honkaiimpact3.hoyoverse.com/tw/zh-tw/download
> 
> 雖然反編譯成功 但 AndroidManifest.xml 檔案內的程式語言碼 對照與您教學影片中的不同 是否能請您分析一下呢?
> 
> AndroidManifest.xml 正常與您教學影片中一致 将libSaber、libArcher这2个文件放入游戏目录assets文件夹内 将com\android\support里的所有smali文件放入游戏文件夹中的android\support
> 
> AndroidManifest.xml 我的檔案和對照截圖 https://drive.google.com/drive/folders/1D2N-ABKLgwRlSfeQ5U8kkyRJjRYkt-oo?usp=share_link

台版有2种APP，所以会出现这种情况，别管，只要根据教程来搞就行了
