### ISSUE TITLE
已根据视频更改文件但是安装到模拟器过后打不开，SEA 服

### ISSUE THREAD

**Issue by Michell-L** [JMBQ/Honkai-Impact-3-mod#5]
已经跟着视频那样修改文件，但是安装到模拟器过后一直闪退，完全进不去游戏，连米哈游那个画面都没出现就闪退了，请问哪里出错了？ SEA 服

**Comment by JMBQ** [comment]
认真看下md，在我没修正assest之前，直装包在模拟器上运行可能会闪退。
使用真机运行即可，如果你非要用模拟器，上雷电9，这货是我当时的测试模拟器，可以运行

**Comment by Michell-L** [comment]
同样是用雷电但我下的是雷4，完美错过！哈哈哈
现在用雷9可以运行，谢谢大佬
