### ISSUE TITLE
Please wait a moment

### ISSUE THREAD

**Issue by AndreiAdii** [JMBQ/Honkai-Impact-3-mod#6]
Option not working, i wait 10 minutes, not working

![Untitled](https://user-images.githubusercontent.com/70166462/202872015-ef2969bb-d5f2-43ef-896d-4e0131490cb5.png)

**Comment by AndreiAdii** [comment]
Used another emulator, used another apk, from their website https://honkaiimpact3.hoyoverse.com/global/en-us/download
Sorry, i don't speak mandarin/chinese. Problem fixed.
![image](https://user-images.githubusercontent.com/70166462/202873525-ec81ce3a-f260-484d-b62d-bb6a810d0156.png)

**Comment by JMBQ** [comment]
hello man，I will fix the bug of emulator Within half a month，Then you can use your own emulator
