### ISSUE TITLE
您好 按照手机教程来DEX编译Plus classes至classes3出现一些问题

### ISSUE THREAD

**Issue by MoonYY-W** [JMBQ/Honkai-Impact-3-mod#7]
![667FB7A691FE6B3B4BE70243D4FBBEDB](https://user-images.githubusercontent.com/57166155/204559565-be8d3aff-6db5-474b-926a-16d977391d05.jpg)
是我的操作失误吗 我是一步一步跟着走的

**Comment by JMBQ** [comment]
你的问题，如果你实在无法自行解决，来MEGA群寻找帮助  https://mega.nz/chat/Iw0VSaab#sWAAwGvtzL9b0jRUGAuo0w

**Comment by MoonYY-W** [comment]
> 你的问题，如果你实在无法自行解决，来MEGA群寻找帮助 https://mega.nz/chat/Iw0VSaab#sWAAwGvtzL9b0jRUGAuo0w

好的 谢谢你
